default and extra format
sillydong/dbdiffer pull request #3
Opened 2021-05-06 03:12 UTC by BeenKilled

2021-05-06 03:23 UTC, sillydong requested changes

2021-05-06 03:23 UTC, sillydong commented on mysql/mysql.go
> +		CurrentTimeStamp = "CURRENT_TIMESTAMP"
在顶部定义const
```
var defaults = map[string]string{
//这里面放extra的内容和format之后内容的对应
...
}
```

2021-05-06 03:23 UTC, sillydong commented on mysql/mysql.go
> +	case &CurrentTimeStamp:
if s == nil{
    return ""
}
if val, exists := defaults[*s];exists{
    return " DEFAULT "+val
}
return " DEFAULT '" + escape(*s) + "'"

2021-05-06 03:23 UTC, sillydong commented on mysql/mysql.go
> +		AutoIncrement = "auto_increment"
参考上面default的做法

2021-05-08 05:14 UTC, BeenKilled commented on mysql/mysql.go
> +		CurrentTimeStamp = "CURRENT_TIMESTAMP"
已修改为数组

2021-05-08 06:00 UTC, sillydong commented on mysql/mysql.go
> +var DefaultStrWithoutQuote = []string{"CURRENT_TIMESTAMP"}
用小写就好了，这些不需要暴露出去

2021-05-08 06:00 UTC, sillydong commented on mysql/mysql.go
> +func ExistInArray(s *string, strArray[] string) (val string, exists bool) {
不用*string，这里应该直接用string

2021-05-08 06:00 UTC, sillydong commented on mysql/mysql.go
> +		if obj == *s {
strings.EqualFold()

2021-05-08 06:24 UTC, BeenKilled commented on mysql/mysql.go
> +func ExistInArray(s *string, strArray[] string) (val string, exists bool) {
![image](https://user-images.githubusercontent.com/26794583/117529205-d71a8b00-b008-11eb-8d6f-cd9cdc0d708b.png)
这个是原来的struct里面是指针导致的，我没动过。不知道是什么原因写成指针，需要一起修改掉吗？

2021-05-08 06:24 UTC, BeenKilled commented on mysql/mysql.go
> +var DefaultStrWithoutQuote = []string{"CURRENT_TIMESTAMP"}
已修改

2021-05-08 07:02 UTC, sillydong approved these changes

2021-05-08 07:02 UTC, merged